Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20120331-1
extra : transplant_source : %F1%9B%60%20p%28E%9Bv%94%B3%82u%D73%8E%A1%E4%E0%D2