Rails3.1: test: add "require 'shoulda/rails'" at test/test_helper.rb
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20120213-7
extra : transplant_source : %A5%81j%9E%A2%F0%B7%0F%DAH%BD%DE%F0%21%D3%08l%1BE%A0